---
ID: 1839a7ed-dd40-45ad-bb21-9b432e0a8a41
Parent: c7c95984-e060-42d9-bbc6-b45c18768905
Template: c82dc5ff-09ef-4403-96d3-3caf377b8c5b
Path: /sitecore/content/Habitat/Settings/searchsettings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20160112T103731Z
    - ID: 498dd5b6-7dae-44a7-9213-1d32596ad14f
      Hint: DatasourceTemplate
      Value: {14E452CA-064D-48A8-9FF2-2744D10437A1}
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: sitecore\admin
    - ID: 5fe1cc43-f86c-459c-a379-cd75950d85af
      Hint: DatasourceLocation
      Value: {0DE95AE4-41AB-4D01-9EB0-67441B7C2450}
