---
ID: c82dc5ff-09ef-4403-96d3-3caf377b8c5b
Parent: df639de8-c9e7-4b18-967e-b1a14a8ff221
Template: ab86861a-6030-46c5-b394-e8f99e8b87db
Path: /sitecore/templates/Foundation/Multisite/Datasource Configuration
SharedFields:
- ID: 06d5295c-ed2f-4a54-9bf2-26228d113318
  # __Icon
  Value: Apps/32x32/Routes.png
- ID: 12c33f3f-86c5-43a5-aeb4-5598cec45116
  # __Base template
  Type: tree list
  Value: |
    {1930BBEB-7805-471A-A3BE-4858AC7CF696}
    {BCCFEBEA-DCCB-48FE-9570-6503829EC03F}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20151223T155629Z
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
