---
ID: e20518bb-1f4d-467f-bae0-11fc2f939c5e
Parent: fff5f245-ffc0-4022-a998-9b07aa5e761f
Template: fff5f245-ffc0-4022-a998-9b07aa5e761f
Path: /sitecore/templates/Foundation/LocalDatasource/Local Datasource Folder/__Standard Values
DB: master
SharedFields:
- ID: 06d5295c-ed2f-4a54-9bf2-26228d113318
  Hint: __Icon
  Value: 
- ID: a791f095-2521-4b4d-bef9-21dda221f608
  Hint: __Style
  Value: color:gray; font-style: italic;
Languages:
- Language: en
  Fields:
  - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
    Hint: __Display name
    Value: Local Content
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20160229T051709Z
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: sitecore\admin
