---
ID: c99275e9-426e-4039-b84a-87335a255bf5
Parent: 92168572-385b-45f0-b40f-3d987ad20e5c
Template: 92168572-385b-45f0-b40f-3d987ad20e5c
Path: /sitecore/templates/Habitat/Project/Website/Page Types/Search Results/__Standard Values
SharedFields:
- ID: f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e
  # __Renderings
  Type: layout
  Value: |
    <r>
      <d id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}" l="{ED043C36-CD48-4EDF-A288-EC404EE1CD42}">
        <r id="{E7AE3F87-CF66-40F2-A9F5-33ECF08BC777}" ph="head" uid="{E6CA18D8-321D-4105-9C38-0622E94BE400}" />
        <r id="{A6CFB41B-C613-4A2B-A5EE-4A374015914D}" ph="page-sidebar" uid="{A1AC1D8A-E47C-4766-8D0F-89BB3BBC9A81}" />
        <r id="{24D6D94B-FF87-4A6C-9AA0-4CBF21488C05}" ph="page-sidebar" uid="{A1AC1D8A-E47C-4766-8D0F-89BB3BBC9A81}" />
        <r id="{3389CAFC-000C-41E5-921C-92821B3DB7B5}" ph="head" uid="{EF51B238-7CE2-4E39-AB87-D05424735160}" />
        <r ds="{DC450599-7C22-4D86-A901-CC8EEC8992C9}" id="{69B9C355-004B-4268-BB1E-2F725B8752B7}" ph="topbarleft" uid="{05FFB7B4-377C-4C00-9520-0ED7735CADCA}" />
        <r id="{53B085DB-6824-4941-9F28-9011CB151832}" ph="navbar" uid="{FBDB4313-35B5-4C26-A586-17F48FD2DC41}" />
        <r id="{A47C8288-7D4C-45FF-B75F-4AEDBF58A02D}" ph="primarymenuheader" uid="{7BD25BD6-C6C4-4FBE-9828-D29A39A2FEC9}" />
        <r id="{2695013C-DD51-410B-9983-F271F16C727D}" ph="primarymenuitems" uid="{3555E24E-FBE9-4D81-AAC7-50408AA45EF0}" />
        <r ds="{9AA07D42-E9B5-4B52-A0E2-4FDF08C203EE}" id="{8C3A2CFC-18FB-4BF5-8584-50EA88978ED6}" ph="primarymenuitems" uid="{9C8A45F2-7008-42C1-8B8A-80A88825C1D8}" />
        <r id="{28BD7068-7FF6-4CE6-98E6-85CFE9967E14}" ph="primarymenuitems" uid="{79242576-4E0A-4CBF-BC2B-8B0C47FE9B64}" />
        <r ds="{575BB28A-B341-40E0-84F4-940DEEFB1B98}" id="{69B9C355-004B-4268-BB1E-2F725B8752B7}" ph="topbarright" uid="{630F4515-1F19-49A8-B986-D46ADD5CE024}" />
        <r id="{A2216CA7-B205-4042-A345-72117D0086C3}" ph="page-layout" uid="{1DF746C3-2D29-43E6-9DE2-05622DED6F97}" />
        <r id="{45B8E1D9-D522-49E0-B9B7-04C965CC7089}" ph="pageheading" uid="{3CDF4DD8-28A4-4185-8C09-A73CAA4633F7}" />
        <r id="{E6BA23C6-08F7-43D0-BE00-BB2129D6F288}" ph="pageheading" uid="{20E3883C-C16D-41D7-B5D3-C4AC60D8386D}" />
        <r id="{CB27D488-5DF8-48B9-B096-D68B2DA637E3}" par="UseStaticPlaceholderNames=1" ph="page-layout" uid="{CBFB049F-39B0-497B-866C-257BAF9CAD52}" />
        <r id="{D460006D-1069-414C-AD24-4821EBA45F70}" ph="col-wide-1" uid="{4FADDAEC-C720-440F-88DA-01BF2E3A08B4}" />
        <r id="{D1AAD687-8B93-44C8-9011-8E8CE2DD281F}" ph="col-narrow-1" uid="{D5246E1F-971A-4B7A-8FE1-FB0AC840AD59}" />
        <r id="{299FD8EA-2CFD-4A69-9CA4-7EA24CD34A46}" ph="footer" uid="{E2040FB7-4151-456D-9315-5973E4EB4D9D}" />
        <r ds="{FB1E4810-6D89-4F1E-A47B-70478FE32DA7}" id="{69B9C355-004B-4268-BB1E-2F725B8752B7}" ph="footercolumn1" uid="{0E0C6DCA-1A29-4975-84D7-E99498A64A72}" />
        <r ds="{B4D87E66-D2C5-4C06-8F9A-08AEAF38055A}" id="{69B9C355-004B-4268-BB1E-2F725B8752B7}" ph="footercolumn1" uid="{0E0C6DCA-1A29-4975-84D7-E99498A64A72}" />
        <r id="{0CF58F14-D0F8-4C41-9896-3D69048A0B19}" ph="footercolumn2" uid="{84124EE2-E678-4144-8316-0D6874866604}" />
        <r id="{3EA717CF-354E-45B1-9A21-BD1D044EA4E2}" ph="footercolumn3" uid="{47F5A079-6F63-4219-BC45-1A221B200906}" />
        <r id="{7DAE9F23-890F-4E06-99A7-CCEDB74D3D8E}" ph="postfooter" uid="{A3BAD4D4-8E21-4B30-8C4C-B04163653D62}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 0ee2f208-1fee-42fc-8051-6696d49a92bf
      # OpenGraphTitle
      Value: $name
    - ID: 1b483e91-d8c4-4d19-ba03-462074b55936
      # NavigationTitle
      Value: $name
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20150911T025049Z
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: 80e30dd8-8021-45f5-9fe1-23d2702cc206
      # SearchBoxTitle
      Value: Enter a text to search for...
    - ID: c30a013f-3cc8-4961-9837-1c483277084a
      # Title
      Value: $name
    - ID: ca0479ce-0bfe-4522-83de-ba688b380a78
      # BrowserTitle
      Value: $name
