---
ID: 9cbf0427-c6b9-42ce-90c6-3d10a48ed3c8
Parent: 920a1781-559f-4e1c-bb2e-6b9a2113fe6b
Template: 920a1781-559f-4e1c-bb2e-6b9a2113fe6b
Path: /sitecore/templates/Project/Common/Content Types/Media/Media Folder/__Standard Values
SharedFields:
- ID: 1172f251-dad4-4efb-a329-0c63500e4f1e
  # __Masters
  Type: TreelistEx
  Value: |
    {F0369E1A-9030-4A05-A09C-EF09B664ED27}
    {F1C095E2-B3E0-46D0-B838-02A9E8B880D9}
    {920A1781-559F-4E1C-BB2E-6B9A2113FE6B}
    {C18D3794-D126-4548-BFC8-89358DE6E9C1}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20150901T053932Z
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
