---
ID: "63de0b0a-3e94-42ec-89ef-f02607530bcf"
Parent: "5df30dc0-e2fc-4921-b8f2-c54fac1bd03e"
Template: "5df30dc0-e2fc-4921-b8f2-c54fac1bd03e"
Path: /sitecore/templates/Feature/Media/ParametersTemplates/_MediaParameters/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160413T164306Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: sitecore\admin
