---
ID: "9a139088-1538-4a97-a596-71ef0ab3f4a5"
Parent: "c80d124b-b9ac-432e-8c26-dbf3a7f18d20"
Template: "c80d124b-b9ac-432e-8c26-dbf3a7f18d20"
Path: /sitecore/templates/Feature/Teasers/_Headline/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160322T023456Z
    - ID: "4a59d072-5b41-4a79-a157-2b2ccac10f2b"
      Hint: TeaserTitle
      Value: $name
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: sitecore\admin
