---
ID: 663a7141-3cca-4115-a062-d7a91c7b8f31
Parent: 9eee8077-990f-4fde-95fb-c7b9819df913
Template: e269fbb5-3750-427a-9149-7aa950b49301
Path: /sitecore/templates/Feature/Social/_TwitterFeedRenderingProperties/Settings
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20151201T122945Z
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
