---
ID: f5c02761-5a45-45c7-a9dc-2c7d0cc48cbf
Parent: 4b67a7f9-7246-4a59-a051-961095c2dc70
Template: a87a00b1-e6db-45ab-8b54-636fec3b5523
Path: /sitecore/content/Habitat/Global/Settings
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20151109T094136Z
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
