---
ID: "d305f6d0-753a-49c6-821a-80dcd09438c1"
Parent: "4738312c-22b8-4e77-9b9c-86bcdcee6635"
Template: "4738312c-22b8-4e77-9b9c-86bcdcee6635"
Path: /sitecore/templates/Foundation/SitecoreExtensions/ParametersTemplate_QueryableDatasourceRendering/__Standard Values
DB: master
SharedFields:
- ID: "3094d236-5985-4c4f-ae6a-e30740885532"
  Hint: Caching
  Value: 0|0|0|0|0|0|0|0
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160226T091732Z
    - ID: "33815197-6029-4010-968e-1165c0e2f4dc"
      Hint: SearchResultsLimit
      Value: 10
