---
ID: d1aad687-8b93-44c8-9011-8e8ce2dd281f
Parent: 5a852bfa-9f18-4b9c-b0af-a60913872b2d
Template: 2a3e91a0-7987-44b5-ab34-35c2d9de83b9
Path: /sitecore/layout/Renderings/Feature/Search/SearchSettings
DB: master
SharedFields:
- ID: 1a7c85e5-dc0b-490d-9187-bb1dbcb4c72f
  Hint: Datasource Template
  Value: 
- ID: 94069f66-609c-48b0-8281-521c30fb269d
  Hint: Open Properties after Add
  Value: 
- ID: b5b27af1-25ef-405c-87ce-369b3a004016
  Hint: Datasource Location
  Value: site:searchsettings
- ID: ded9e431-3604-4921-a4b3-a6ec7636a5b6
  Hint: Controller Action
  Value: SearchSettings
- ID: e64ad073-dfcc-4d20-8c0b-fe5aa6226cd7
  Hint: Controller
  Value: Sitecore.Feature.Search.Controllers.SearchController, Sitecore.Feature.Search
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20150911T032830Z
