---
ID: cae7dae3-deb2-4415-b118-a2069bdb174a
Parent: 49c651ba-4004-40a9-9b0f-e95d0573f3ae
Template: 49c651ba-4004-40a9-9b0f-e95d0573f3ae
Path: /sitecore/templates/Project/Habitat/Page Types/Demo Page/__Standard Values
SharedFields:
- ID: 1172f251-dad4-4efb-a329-0c63500e4f1e
  # __Masters
  Type: TreelistEx
  Value: |
    {49C651BA-4004-40A9-9B0F-E95D0573F3AE}
    {51B1726B-4290-4908-A2DA-B169194AE80C}
    {7DEFAA26-ED9D-4495-B5F0-0A7620403842}
    {3F3CAE5E-63D2-4F75-95D9-23EB01827AA9}
- ID: b0a67b2a-8b07-4e0b-8809-69f751709806
  # __Tracking
  Type: Tracking
  Value: "<tracking ignore=\"1\" />"
- ID: f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e
  # __Renderings
  Type: layout
  Value: |
    <r>
      <d id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}" l="{BA43C26B-3A61-4F96-A83A-60193978B66C}">
        <r id="{B883E272-70D8-419A-8AF8-819356D839AD}" ph="content" uid="{3FC98F56-C7C2-480C-9769-6BD25FBDD390}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20151110T000242Z
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
