---
ID: "02c1eb45-495a-4e40-9530-3be02015f61c"
Parent: "a2a233a1-6701-48a9-b5f8-efeab74b655f"
Template: "a2a233a1-6701-48a9-b5f8-efeab74b655f"
Path: /sitecore/templates/Foundation/Theming/ParametersTemplate_HasBackground/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160323T004949Z
