---
ID: 3acba3a7-fd6c-4c3e-ae68-da2aa6c3ae95
Parent: 4654d5f0-9b39-426a-992d-1d42e356fb0a
Template: 4654d5f0-9b39-426a-992d-1d42e356fb0a
Path: /sitecore/templates/Project/Common/Parameters/Layout/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20150921T024007Z
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: extranet\Anonymous
