---
ID: af244e6f-ef24-4e60-8c85-ff18a9d8a54f
Parent: 4c82b6dd-fe7c-4144-bcb3-f21b4080568f
Template: 4c82b6dd-fe7c-4144-bcb3-f21b4080568f
Path: /sitecore/templates/Foundation/Multisite/Settings Folder/__Standard Values
SharedFields:
- ID: 1172f251-dad4-4efb-a329-0c63500e4f1e
  # __Masters
  Type: TreelistEx
  Value: {05DB4668-538B-4E6E-9C89-B6AB7374AA3C}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20160105T043436Z
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
