---
ID: 6912dbc9-587b-448c-a49d-0fb43f446301
Parent: d1d3e60f-e571-48d2-84cf-b053ee660c13
Template: d1d3e60f-e571-48d2-84cf-b053ee660c13
Path: /sitecore/templates/Habitat/Domain/Search/_PagedSearchResultsParameters/__Standard Values
SharedFields:
- ID: 3094d236-5985-4c4f-ae6a-e30740885532
  # Caching
  Value: 0|0|0|0|0|0|0|0
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20151126T130538Z
    - ID: d7dde02f-b1f1-416d-91e0-7c3612ef4871
      # PagesToShow
      Value: 5
    - ID: fcc7e3b4-46ab-4a51-975f-a6b259b3d214
      # ResultsOnPage
      Value: 4
