---
ID: 4eabf0f3-1374-4467-be9c-1f322b8d0966
Parent: 41da2d61-d85a-40f1-be69-ddd18dd1bc93
Template: 41da2d61-d85a-40f1-be69-ddd18dd1bc93
Path: /sitecore/templates/Project/Common/Content Types/FAQ Folder/__Standard Values
DB: master
SharedFields:
- ID: 1172f251-dad4-4efb-a329-0c63500e4f1e
  Hint: __Masters
  Type: TreelistEx
  Value: {BFDC1F27-3D2D-495F-89A3-0951F882420B}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20160301T105718Z
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      Hint: __Created by
      Value: sitecore\admin
