---
ID: 2b43e87c-e0c5-48e8-865f-3322ee929660
Parent: 0db13819-7df3-4136-a4b9-0a22b1023ef7
Template: 0db13819-7df3-4136-a4b9-0a22b1023ef7
Path: /sitecore/templates/Habitat/Project/Website/Content Types/InterestsFolder/__Standard Values
SharedFields:
- ID: 06d5295c-ed2f-4a54-9bf2-26228d113318
  # __Icon
  Value: applications/32x32/folder_ok.png
- ID: 1172f251-dad4-4efb-a329-0c63500e4f1e
  # __Masters
  Type: TreelistEx
  Value: {4176BFC2-7814-4FA5-ABCF-7FA0714BF05F}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20151112T134525Z
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
