---
ID: 88964325-022e-47c9-bd85-1e46493e1168
Parent: f1c095e2-b3e0-46d0-b838-02a9e8b880d9
Template: f1c095e2-b3e0-46d0-b838-02a9e8b880d9
Path: /sitecore/templates/Habitat/Project/Website/Content Types/Media/Video/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20150901T053456Z
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
