---
ID: c29896fb-878c-4d74-9c7b-0dccbb831970
Parent: 0643d9d4-f30b-4b07-91d0-289cc324c9cf
Template: 0643d9d4-f30b-4b07-91d0-289cc324c9cf
Path: /sitecore/templates/Habitat/Project/Website/Content Types/Site Root/__Standard Values
SharedFields:
- ID: 1172f251-dad4-4efb-a329-0c63500e4f1e
  # __Masters
  Type: TreelistEx
  Value: |
    {4A8822CC-B418-4452-AB0F-8BB6DF2F2114}
    {BF8FC165-5C6C-4F92-9FF9-E5B4AAE68887}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20140305T094105
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
