---
ID: "5d1a8070-2337-46f9-a828-d1d0425aea34"
Parent: "c18d3794-d126-4548-bfc8-89358de6e9c1"
Template: "c18d3794-d126-4548-bfc8-89358de6e9c1"
Path: /sitecore/templates/Project/Common/Content Types/Media/Carousel/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {F0369E1A-9030-4A05-A09C-EF09B664ED27}
    {F1C095E2-B3E0-46D0-B838-02A9E8B880D9}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160829T052837Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: sitecore\admin
